export type AttachmentArchiveItem = {
  id: string;
  category: "수술실" | "격리실" | "중환자실" | "기타";
  title: string;
  image: string;
  thumbnail: string;
  sourceGroup: string;
  sourceFile: string;
  sourceType: string;
  usage: "representative" | "archive";
};
export const attachmentArchive: AttachmentArchiveItem[] = [
  {
    "id": "archive-001",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-001.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-001.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-002",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-002.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-002.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1426820594908.jpeg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-003",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-003.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-003.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1426820610569.jpeg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-004",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-004.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-004.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1426820620358.jpeg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-005",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-005.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-005.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1426820627148.jpeg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-006",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-006.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-006.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1505288992389.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-007",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-007.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-007.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1540338362514.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-008",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-008.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-008.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1540338372234.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-009",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-009.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-009.webp",
    "sourceGroup": "수술실",
    "sourceFile": "1543992167936.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-010",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-010.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-010.webp",
    "sourceGroup": "수술실",
    "sourceFile": "2.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-011",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-011.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-011.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20140822_131955.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-012",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-012.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-012.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20140822_132055.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-013",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-013.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-013.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20140828_153510.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-014",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-014.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-014.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20140828_153526.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-015",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-015.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-015.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20150303_094001.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-016",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-016.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-016.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20150303_094135.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-017",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-017.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-017.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20150330_075916.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-018",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-018.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-018.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20151216_120455.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-019",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-019.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-019.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20151216_120524.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-020",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-020.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-020.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20151220_080513.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-021",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-021.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-021.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20151220_080532.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-022",
    "category": "수술실",
    "title": "수술실 골조·천장 시공 과정",
    "image": "/images/archive/kenc-archive-022.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-022.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20160104_064542.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-023",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-023.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-023.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20170308_100407.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-024",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-024.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-024.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20190113_104439.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-025",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-025.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-025.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20190410_084958.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-026",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-026.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-026.webp",
    "sourceGroup": "수술실",
    "sourceFile": "20191004_070719.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-027",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-027.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-027.webp",
    "sourceGroup": "수술실",
    "sourceFile": "3.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-028",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-028.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-028.webp",
    "sourceGroup": "수술실",
    "sourceFile": "4.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-029",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-029.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-029.webp",
    "sourceGroup": "수술실",
    "sourceFile": "5.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-030",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-030.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-030.webp",
    "sourceGroup": "수술실",
    "sourceFile": "6.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-031",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-031.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-031.webp",
    "sourceGroup": "수술실",
    "sourceFile": "7.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-032",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-032.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-032.webp",
    "sourceGroup": "수술실",
    "sourceFile": "8.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-033",
    "category": "수술실",
    "title": "병동·중환자실 참고 공간",
    "image": "/images/archive/kenc-archive-033.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-033.webp",
    "sourceGroup": "수술실",
    "sourceFile": "IMG_3620.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-034",
    "category": "수술실",
    "title": "병동·중환자실 참고 공간",
    "image": "/images/archive/kenc-archive-034.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-034.webp",
    "sourceGroup": "수술실",
    "sourceFile": "IMG_3622.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-035",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-035.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-035.webp",
    "sourceGroup": "수술실",
    "sourceFile": "P2.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-036",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-036.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-036.webp",
    "sourceGroup": "수술실",
    "sourceFile": "P3.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-037",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-037.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-037.webp",
    "sourceGroup": "수술실",
    "sourceFile": "P4.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-038",
    "category": "수술실",
    "title": "수술실 3D 설계 도면",
    "image": "/images/archive/kenc-archive-038.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-038.webp",
    "sourceGroup": "수술실",
    "sourceFile": "P5.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-039",
    "category": "수술실",
    "title": "수술실 완공·장비 설치 사진",
    "image": "/images/archive/kenc-archive-039.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-039.webp",
    "sourceGroup": "수술실",
    "sourceFile": "SNV82564-1.JPG",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-040",
    "category": "중환자실",
    "title": "중환자실 공간 자료",
    "image": "/images/archive/kenc-archive-040.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-040.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "1505288997411.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-041",
    "category": "중환자실",
    "title": "중환자실 간호 스테이션·병상 구역",
    "image": "/images/archive/kenc-archive-041.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-041.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20180621_074445.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-042",
    "category": "중환자실",
    "title": "중환자실 간호 스테이션·병상 구역",
    "image": "/images/archive/kenc-archive-042.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-042.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20180621_074457.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-043",
    "category": "중환자실",
    "title": "중환자실 간호 스테이션·병상 구역",
    "image": "/images/archive/kenc-archive-043.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-043.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20180625_113541.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-044",
    "category": "중환자실",
    "title": "중환자실 공간 자료",
    "image": "/images/archive/kenc-archive-044.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-044.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20180917_133755.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-045",
    "category": "중환자실",
    "title": "중환자실 청정 구역 마감",
    "image": "/images/archive/kenc-archive-045.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-045.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20190426_120342.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-046",
    "category": "중환자실",
    "title": "중환자실 청정 구역 마감",
    "image": "/images/archive/kenc-archive-046.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-046.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "20190426_120402.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-047",
    "category": "중환자실",
    "title": "운영 중 중환자실 전경",
    "image": "/images/archive/kenc-archive-047.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-047.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "IMG_3620.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-048",
    "category": "중환자실",
    "title": "운영 중 중환자실 전경",
    "image": "/images/archive/kenc-archive-048.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-048.webp",
    "sourceGroup": "중환자실",
    "sourceFile": "IMG_3622.jpg",
    "sourceType": "원본 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-049",
    "category": "격리실",
    "title": "음압병상 중앙관제 화면",
    "image": "/images/archive/kenc-archive-049.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-049.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image1.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-050",
    "category": "격리실",
    "title": "음압병실 의료진 입구",
    "image": "/images/archive/kenc-archive-050.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-050.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image10.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-051",
    "category": "격리실",
    "title": "격리실 화장실·세면 설비",
    "image": "/images/archive/kenc-archive-051.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-051.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image11.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-052",
    "category": "격리실",
    "title": "음압병실 급배기 설비",
    "image": "/images/archive/kenc-archive-052.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-052.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image12.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-053",
    "category": "격리실",
    "title": "입구 출입통제·차압계",
    "image": "/images/archive/kenc-archive-053.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-053.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image13.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-054",
    "category": "격리실",
    "title": "전실 출입통제·너스콜",
    "image": "/images/archive/kenc-archive-054.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-054.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image14.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-055",
    "category": "격리실",
    "title": "폐수탱크 펌프 설비",
    "image": "/images/archive/kenc-archive-055.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-055.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image15.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-056",
    "category": "격리실",
    "title": "폐수탱크 드레인 배관",
    "image": "/images/archive/kenc-archive-056.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-056.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image16.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-057",
    "category": "격리실",
    "title": "폐수 설비 골조 시공",
    "image": "/images/archive/kenc-archive-057.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-057.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image17.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-058",
    "category": "격리실",
    "title": "폐수탱크 배관·밸브",
    "image": "/images/archive/kenc-archive-058.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-058.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image18.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-059",
    "category": "격리실",
    "title": "소독 약품 탱크 설비",
    "image": "/images/archive/kenc-archive-059.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-059.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image19.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-060",
    "category": "격리실",
    "title": "음압격리실 공조 제어 화면",
    "image": "/images/archive/kenc-archive-060.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-060.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image2.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-061",
    "category": "격리실",
    "title": "격리실 공조기·배기팬",
    "image": "/images/archive/kenc-archive-061.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-061.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image20.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-062",
    "category": "격리실",
    "title": "음압병실 복도 동선",
    "image": "/images/archive/kenc-archive-062.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-062.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image3.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-063",
    "category": "격리실",
    "title": "의료진 출입구 전실",
    "image": "/images/archive/kenc-archive-063.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-063.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image4.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-064",
    "category": "격리실",
    "title": "음압병실 출입 자동문",
    "image": "/images/archive/kenc-archive-064.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-064.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image5.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-065",
    "category": "격리실",
    "title": "음압병실 병상 내부",
    "image": "/images/archive/kenc-archive-065.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-065.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image6.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-066",
    "category": "격리실",
    "title": "격리실 전실 복도",
    "image": "/images/archive/kenc-archive-066.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-066.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image7.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-067",
    "category": "격리실",
    "title": "환자전용 출입 동선",
    "image": "/images/archive/kenc-archive-067.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-067.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image8.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-068",
    "category": "격리실",
    "title": "음압병실 출입문·세면대",
    "image": "/images/archive/kenc-archive-068.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-068.webp",
    "sourceGroup": "격리실/격리실.pptx",
    "sourceFile": "image9.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-069",
    "category": "기타",
    "title": "공사구역 철거 작업",
    "image": "/images/archive/kenc-archive-069.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-069.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image1.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-070",
    "category": "기타",
    "title": "수술실 파티클 측정",
    "image": "/images/archive/kenc-archive-070.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-070.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image10.jpg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-071",
    "category": "기타",
    "title": "수술실·클린룸 장비 점검",
    "image": "/images/archive/kenc-archive-071.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-071.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image11.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-072",
    "category": "기타",
    "title": "폐기물 하역 작업",
    "image": "/images/archive/kenc-archive-072.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-072.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image2.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-073",
    "category": "기타",
    "title": "철거 후 바닥 하도 작업",
    "image": "/images/archive/kenc-archive-073.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-073.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image3.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-074",
    "category": "기타",
    "title": "바닥 셀프레벨링 작업",
    "image": "/images/archive/kenc-archive-074.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-074.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image4.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-075",
    "category": "기타",
    "title": "소음 측정 기록",
    "image": "/images/archive/kenc-archive-075.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-075.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image5.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-076",
    "category": "기타",
    "title": "차압 측정 기록",
    "image": "/images/archive/kenc-archive-076.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-076.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image6.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-077",
    "category": "기타",
    "title": "필터 교체 작업",
    "image": "/images/archive/kenc-archive-077.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-077.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image7.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-078",
    "category": "기타",
    "title": "클린룸 철거 후 바닥 작업",
    "image": "/images/archive/kenc-archive-078.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-078.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image8.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-079",
    "category": "기타",
    "title": "SGP 패널 색상표",
    "image": "/images/archive/kenc-archive-079.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-079.webp",
    "sourceGroup": "기타/기타자료.pptx",
    "sourceFile": "image9.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-080",
    "category": "기타",
    "title": "공사구역 철거 작업",
    "image": "/images/archive/kenc-archive-080.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-080.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image1.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-081",
    "category": "기타",
    "title": "기타 시공·유지관리 자료",
    "image": "/images/archive/kenc-archive-081.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-081.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image10.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-082",
    "category": "기타",
    "title": "수술실·클린룸 장비 점검",
    "image": "/images/archive/kenc-archive-082.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-082.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image11.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-083",
    "category": "기타",
    "title": "기타 시공·유지관리 자료",
    "image": "/images/archive/kenc-archive-083.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-083.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image12.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-084",
    "category": "기타",
    "title": "그린 수술실 모니터 전경",
    "image": "/images/archive/kenc-archive-084.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-084.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image13.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-085",
    "category": "기타",
    "title": "화이트 수술실 수술등",
    "image": "/images/archive/kenc-archive-085.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-085.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image14.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-086",
    "category": "기타",
    "title": "블루 수술실 장비 배치",
    "image": "/images/archive/kenc-archive-086.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-086.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image15.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-087",
    "category": "기타",
    "title": "스테인리스 수납장 마감",
    "image": "/images/archive/kenc-archive-087.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-087.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image16.png",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-088",
    "category": "기타",
    "title": "폐기물 하역 작업",
    "image": "/images/archive/kenc-archive-088.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-088.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image2.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-089",
    "category": "기타",
    "title": "철거 후 바닥 하도 작업",
    "image": "/images/archive/kenc-archive-089.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-089.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image3.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-090",
    "category": "기타",
    "title": "바닥 셀프레벨링 작업",
    "image": "/images/archive/kenc-archive-090.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-090.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image4.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-091",
    "category": "기타",
    "title": "소음 측정 기록",
    "image": "/images/archive/kenc-archive-091.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-091.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image5.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-092",
    "category": "기타",
    "title": "차압 측정 기록",
    "image": "/images/archive/kenc-archive-092.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-092.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image6.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-093",
    "category": "기타",
    "title": "필터 교체 작업",
    "image": "/images/archive/kenc-archive-093.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-093.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image7.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-094",
    "category": "기타",
    "title": "클린룸 철거 후 바닥 작업",
    "image": "/images/archive/kenc-archive-094.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-094.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image8.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  },
  {
    "id": "archive-095",
    "category": "기타",
    "title": "SGP 패널 색상표",
    "image": "/images/archive/kenc-archive-095.webp",
    "thumbnail": "/images/archive/thumbs/kenc-archive-095.webp",
    "sourceGroup": "회사명.pptx",
    "sourceFile": "image9.jpeg",
    "sourceType": "PPT 내부 이미지",
    "usage": "archive"
  }
] as AttachmentArchiveItem[];

export const attachmentArchiveSummary = {
  total: 95,
  "수술실": 39,
  "격리실": 20,
  "중환자실": 9,
  "기타": 27,
};
